### ISSUE TITLE
Macros get truncated

### ISSUE THREAD

**Issue by ben0x539** [Oppzippy/GlobalSearch#46] opened 2024-10-09 00:31 UTC
Searching for and trying to run a macro has been failing to me with the macro seemingly getting truncated before being executed. I think this is because of the [change to the macrotext attribute to have the 255 characters limit like regular macros](https://warcraft.wiki.gg/wiki/Patch_11.0.2/API_changes#Breaking_changes) together with the `/run LibStub("AceAddon-3.0"):GetAddon("GlobalSearch"):GetModule("Search"):OnMacroItemSelected(...)` preamble. I have no clue if it's possible to work around that entirely, for my own use with only-somewhat-long macros I'm mitigating it by stashing that function in a global with a shorter name...

**Comment by Oppzippy** [comment] 2024-10-09 02:10
Yeah, that macrotext change was the cause. Fixed in v0.23.11 by hooking `InsecureActionButtonTemplate`'s `OnClick` script instead of adding the preamble to the macro.

**Closed by Oppzippy** 2024-10-09 02:10 UTC
